name: New version

on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: echo running on branch ${github.head_ref}
